### ISSUE TITLE
Filter by tags

### ISSUE THREAD

**Issue by andi357** [phrase/phraseapp-client#10]
I have two localizable files in my iOS project. The first one is the `Localizable.strings` file, wich can be easily updated by using `phraseapp pull`.

The second one is the `InfoPlist.strings` file that contains localizations e.g. for the `NSCalendarsUsageDescription` of the project's `Info.plist`. Currently I don't see any other chance than creating a second PhraseApp project for this file.

I wish I could set tags within the `phrasapp.yml` to filter keys with that specified tag for an output file.

For example like this:

```
phraseapp:
  access_token: "<token>"
  project_id: "<project_id>"
  file_format: "yml"
  pull:
    targets:
    - file: "./<locale_code>.lproj/Localizable.strings"
      params:
        tags: ["app-keys"]
    - file: "./<locale_code>.lproj/InfoPlist.strings"
      params:
        tags: ["info-plist-keys"]
```

This would create `Localizable.strings` files with all keys that belong to the `app-keys` tag and `InfoPlist.strings` that belong to the `info-plist-keys` tag.

**Comment by docstun** [comment]
The `pull` command only supports one `tag` since it relies on the parameters from the [locales#download endpoint](http://docs.phraseapp.com/api/v2/locales/#download), so you should be able to specify your targets like this:

```
phraseapp:
  access_token: "<token>"
  project_id: "<project_id>"
  file_format: "yml"
  pull:
    targets:
    - file: "./<locale_code>.lproj/Localizable.strings"
      params:
        tag: app-keys
    - file: "./<locale_code>.lproj/InfoPlist.strings"
      params:
        tag: info-plist-keys
```

Does that solve the problem?
