### ISSUE TITLE
phrase pull by specific tag

### ISSUE THREAD

**Issue by ricardolyn** [phrase/phraseapp-client#104]
Hey,

I know that `phraseapp pull` uses the yml, but sometimes I want that based on the YML configuration, pull only this specific tag (appended to the YML one) without pulling all strings or changing the YML for this, using the same files and not dividing by features.

If we divide by files, it will be a complicate configuration and number of files, as there are several teams with several features working at the same time, so isn't scalable.

**Comment by tobstarr** [comment]
Thank you for contacting us, we will get back to you soon

**Comment by theSoenke** [comment]
Hi @walling, just to make sure I understand it correctly. Basically when you provide are downloading locales you want to add a tag like `phraseapp pull --tag mytag` and then the tag for all locale targets should be set to `mytag` correct?

**Comment by walling** [comment]
@theSoenke Ok, maybe I misunderstood the original poster. Our use case is basically to be able to filter on a specific tag. Let's say we have the following configuration with multiple targets:

```
phraseapp:
  access_token: SOME_TOKEN
  project_id: SOME_ID
  pull:
    targets:
      - file: ./apps/src/xxx/locales/<locale_name>.json
        params:
          tag: "react_xxx"
          file_format: node_json

      - file: ./apps/src/yyy/locales/<locale_name>.json
        params:
          tag: "react_yyy"
          file_format: node_json

      - file: ./apps/src/zzz/locales/<locale_name>.json
        params:
          tag: "react_zzz"
          file_format: node_json
```

With `phraseapp pull` it updates all files and we need to use git to reset some of the files. Basically, it would simplify the process, if we could specify `phraseapp pull --tag react_zzz` and only pull those locale files. Another solution would be to name each target and then specify `--target zzz` (just an example). What do you think?
