### ISSUE TITLE
Bug: using tag variable inside push config will tag all keys with all tags

### ISSUE THREAD

**Issue by gbrehmer** [phrase/phraseapp-client#117]
my config

```
phraseapp:
  access_token: xxx
  project_id: xxx
  push:
    sources:
    - file: ./src/main/webapp/i18n/de/<tag>.json
      params:
        file_format: nested_json
        locale_id: de
    - file: ./src/main/webapp/i18n/en/<tag>.json
      params:
        file_format: nested_json
        locale_id: en
```

console call:

```
phraseapp push
```
