### ISSUE TITLE
Don't pull base language?

### ISSUE THREAD

**Issue by ajb** [phrase/phraseapp-client#12]
How can I configure the client to not pull my base language?

**Comment by docstun** [comment]
I guess the best way would be to define each locale explicitly in your `.phraseapp.yml` config file, e.g:

```
...
pull:
  targets:
    - 
      file: /path/to/your/file/en.json
      locale_id: en
    - 
      file: /path/to/your/file/fr.json
      locale_id: fr
```

Does that solve your problem?

**Comment by ajb** [comment]
Sure. Thanks!

On Thu, Aug 27, 2015 at 8:54 AM, Manuel Boy <notifications@github.com>
wrote:

> I guess the best way would be to define each locale explicitly in your
> .phraseapp.yml config file, e.g:
>
> ...
> pull:
>   targets:
>     -
>       file: /path/to/your/file/en.json
>       locale_id: en
>     -
>       file: /path/to/your/file/fr.json
>       locale_id: fr
>
> Does that solve your problem?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/phrase/phraseapp-client/issues/12#issuecomment-135413938>
> .
>



-- 
Adam Becker
(951) 9-BECKER
@AdamJacobBecker

**Comment by ajb** [comment]
Hm. With this config:

![img](http://take.ms/R4O44)

I'm seeing this:

![img](http://take.ms/QR4KtJ)

**Comment by Pertel** [comment]
According to the [documentation for targets] (http://docs.phraseapp.com/developers/cli/configuration/#targets), the only valid formats for the file parameter is with a `<locale_name>` or `<locale_code>` placeholder. I would also like to both pull and push specific files, instead of all locales in a folder.

**Comment by kennell** [comment]
@Pertel you can push/pull specific locales and save them to a custom path (including the Placeholders). Example:

```yaml
...
  pull:
    targets:
    - file: ./foo/<locale_name>/<locale_code>.yml
      params:
        locale_id: en-GB
    - file: ./bar/<locale_name>/<locale_code>.yml
      params:
        locale_id: es-ES
    - file: ./qux/<locale_name>/<locale_code>.yml
      params:
        locale_id: fr-FR

```
