### ISSUE TITLE
Misleading error message when config is badly formatted

### ISSUE THREAD

**Issue by tronje** [phrase/phraseapp-client#126]
Consider the following snippet:

```yml
phraseapp:
access_token: xxx
project_id: xxx
push:
sources:
- file: /path/to/file
params:
file_format: strings
locale_id: xxx
```

Otherwise correct, it is missing required indentation. When using such a config, the client generates the following error message:
`ERROR: This should not have happened: reflect: reflect.Value.Set using unaddressable value - Contact support: support@phraseapp.com`

Generating an error is obviously fine, but the error message is neither useful nor correct.
The error message should express that there is an issue with the config, and ideally also give a hint about what the issue is, like mentioning that sections under `phraseapp` are missing.
