### ISSUE TITLE
Tags parameter does not work on pull

### ISSUE THREAD

**Issue by iamandrewluca** [phrase/phraseapp-client#148]
> This issue I also reported to online support chat

`.phraseapp.yml` configuration

```yaml
phraseapp:
  access_token: "..."
  project_id: "..."
  file_format: "xlf"
  push:
    sources:
    - file: "./packages/<tag>/Resources/Private/Language/en.locallang.xlf"
    - file: "./packages/my_template/Resources/Private/Overrides/<tag>/Language/en.locallang.xlf"
  pull:
    targets:
    - file: "./packages/my_template/Resources/Private/Language/<locale_code>.locallang.xlf"
      params:
        tags:
        - "my_template"
    - file: "./packages/my_template/Resources/Private/Overrides/<tag>/Language/<locale_code>.locallang.xlf"
      params:
        tags:
        - "my_events"
        - "my_news"
```

I executed `phraseapp push --wait` and got the right results

```bash
Uploading packages/my_template/Resources/Private/Language/en.locallang.xlf...
Upload ID: 990...912, filename: en.locallang.xlf suceeded. Waiting for your file to be processed...
Successfully uploaded and processed packages/my_template/Resources/Private/Language/en.locallang.xlf.
Uploading packages/my_template/Resources/Private/Overrides/my_events/Language/en.locallang.xlf...
Upload ID: 1e7...7f5, filename: en.locallang.xlf suceeded. Waiting for your file to be processed...
Successfully uploaded and processed packages/my_template/Resources/Private/Overrides/my_events/Language/en.locallang.xlf.
Uploading packages/my_template/Resources/Private/Overrides/my_news/Language/en.locallang.xlf...
Upload ID: 7b2...48c, filename: en.locallang.xlf suceeded. Waiting for your file to be processed...
Successfully uploaded and processed packages/my_template/Resources/Private/Overrides/my_news/Language/en.locallang.xlf.
```

When I try to pull (`phraseapp pull`) I get this error

```bash
ERROR: configuration key "tags" has invalid value: []interface {}
see https://phraseapp.com/docs/developers/cli/configuration/
```

As [docs](https://help.phraseapp.com/phraseapp-for-developers/phraseapp-client/configuration) states

> The pull command also supports all parameters that are available for the locales#download API endpoint.

**Note:**
locales#download link goes to <https://developers.phraseapp.com/api/#locales>
That does not exist. There is <https://developers.phraseapp.com/api/#locales_download>

As docs in second link states

> |Name|Type|Description|
> |---|---|---|
> |tag optional|string|This parameter is deprecated. Please use the "tags" parameter instead|

And I used `tags` instead

This example works on push/pull, but I have to add an entry for each file

```yaml
phraseapp:
  access_token: "..."
  project_id: "..."
  file_format: "xlf"
  push:
    sources:
    - file: "./packages/<tag>/Resources/Private/Language/en.locallang.xlf"
    - file: "./packages/my_template/Resources/Private/Overrides/<tag>/Language/en.locallang.xlf"
  pull:
    targets:
    - file: "./packages/my_template/Resources/Private/Language/<locale_code>.locallang.xlf"
      params:
        tag: "my_template"
    - file: "./packages/my_template/Resources/Private/Overrides/my_events/Language/<locale_code>.locallang.xlf"
      params:
        tag: "my_events"
    - file: "./packages/my_template/Resources/Private/Overrides/my_news/Language/<locale_code>.locallang.xlf"
      params:
        tag: "my_news"

**Comment by theSoenke** [comment]
Hi @iamandrewluca, the client expects a comma-separated list of tags. For example: `tags: tag1,tag2`. A YAML array of tags is currently not supported by the client. Please make also sure that you are using the latest version of the client 1.11.1 when using multiple tags.

**Comment by iamandrewluca** [comment]
@theSoenke Ok, I tried new syntax but no chance. I tried all of this, no one worked

```yaml
tags: my_events,my_news,my_products,my_references,my_segments # no quotes, no spaces
tags: my_events, my_news, my_products, my_references, my_segments # no quotes, spaces
tags: "my_events,my_news,my_products,my_references,my_segments" # quotes, no spaces
tags: "my_events, my_news, my_products, my_references, my_segments" # quotes, spaces
tags: # yaml array format
- "my_events"
- "my_news"
- "my_products"
- "my_references"
- "my_segments"
```

First 4 cases I got this error

```bash
⇒  phraseapp pull
ERROR: Using <tag> placeholder but no tags were provided. Please specify a 'tag: "my_tag"' in the params section.
```

Last case error

```bash
⇒  phraseapp pull
ERROR: configuration key "tags" has invalid value: []interface {}
see https://phraseapp.com/docs/developers/cli/configuration/
```

If I use `tag` instead of `tags` and give more of them `"my_events,my_news", it tries to find a tag with this name `my_events,my_news`

Looked int ocodebase and no mention of `tags`, found only this

https://github.com/phrase/phraseapp-client/blob/0df7d1278253d9e1587ed26eff56b047b7c8539f/pull_target.go#L90-L96

It seems `tags` are not implemented yet into `cli`

**Comment by iamandrewluca** [comment]
Only push command has `tags` param as a comma separated list of tags that will be added to new keys

![image](https://user-images.githubusercontent.com/1881266/46792985-43e42080-cd4d-11e8-9996-9d2a27ac971b.png)

**Comment by theSoenke** [comment]
@iamandrewluca The newest release should now support the `tags` parameter in placeholders correctly. Let me know in case you should still notice any issue https://github.com/phrase/phraseapp-client/releases/tag/1.12.0

**Comment by iamandrewluca** [comment]
I updated to new PhraseApp binary. It seems it does not work. How version is checked from cli?
```yaml
pull:
  targets:
  - file: "./packages/<tag>/Resources/Private/Language/<locale_code>.locallang.xlf"
    params:
      tags: "my_template,my_whitelabels"

  - file: "./packages/my_template/Resources/Private/Overrides/<tag>/Language/<locale_code>.locallang.xlf"
    params:
      tags: "my_events,my_news,my_products,my_references,my_segments"
```
```bash
Downloaded de to packages/Resources/Private/Language/de.locallang.xlf
Downloaded en to packages/Resources/Private/Language/en.locallang.xlf
Downloaded es to packages/Resources/Private/Language/es.locallang.xlf
Downloaded pl to packages/Resources/Private/Language/pl.locallang.xlf
Downloaded de to packages/my_template/Resources/Private/Overrides/Language/de.locallang.xlf
Downloaded en to packages/my_template/Resources/Private/Overrides/Language/en.locallang.xlf
Downloaded es to packages/my_template/Resources/Private/Overrides/Language/es.locallang.xlf
Downloaded pl to packages/my_template/Resources/Private/Overrides/Language/pl.locallang.xlf
```

I also would recommend to trim tags when you split them by comma
```yaml
tags: "my_template, my_whitelabels"
```
Will try to search tag ` my_whitelabels` (with a space in front)
