### ISSUE TITLE
Feature request: Allow explicit exclusion of locales in CLI & its yml file

### ISSUE THREAD

**Issue by GeroHerkenrath** [phrase/phraseapp-client#168]
This has come up in two other (now closed) issues, so I'll add a new request for this.
I'd really appreciate it if I could exclude specific locales from `push` and `pull` when using the CLI, at least when pulling. I could imagine something like this for the YAML config file:

```
phraseapp:
  file_format: xml
  project_id: ...
  pull:
    targets:
    - file: ./app/src/main/res/values-<locale_code>/strings.xml
      params:
        exclude: en
  push:
    sources:
    - file: ./app/src/main/res/values/strings.xml
      params:
        locale_id: ...
```

The `exclude` part would be new, I wouldn't care much how the locale is specified there (it could also be the id, like in the `push` section). The reason why I cannot just "whilelist" the other locales instead of excluding that one would be that I don't necessarily know how many locales there are. Those should be added by our localizers directly in PhraseApp, without having the need to update the YAML.

The related issues were #12 and #27. I am in a similar position, i.e. I don't want to `pull` the default language/locale in an Android project. As above YAML shows, instead I also only `push` said default. 

That way, we have a "single point of truth" for the "input" for our localization team. They also use git sync, so PhraseApp actually does the `pull` for us most of the time. It's not a big deal having the default language kind of "doubled" in the project (once as default, once as explicit en locale in `./app/src/main/res/values-en/strings.xml` after a `pull`), but it would be cleaner and nicer to be able to omit that. Currently we devs manually go into the PRs created via PhraseApp, delete the superfluous en locale, commit & push and then merge the PR, but I see the day coming we forget that. 😄

**Comment by theSoenke** [comment]
Hi @GeroHerkenrath, thanks for your detailed explanation. This case seems to be very Android specific due to the required default strings file. How much of an issue is it for you to have the en translations two times in your app? The size should usually be negligible and the file `./app/src/main/res/values-en/strings.xml`. When you include both files there also would no need to manually delete the file :)

**Comment by GeroHerkenrath** [comment]
Hello @theSoenke, thanks for responding. Yes, this case is kind of Android specific and having two en-files is not that big of an issue. At the moment we manually checkout the branch PhraseApp creates when new translations arrive (for testing purposes), so we will probably just delete the second one manually anyway.

This request certainly does not have a high priority for us and neither should it have that for you. I just wanted to "formally let you know", especially since I saw two older issues with a similar aspect. I also figured that perhaps it's not that difficult for you to implement as it's basically just "excluding some locales from a loop" in the CLI, but of course I realize that's no more than a guess (and perhaps plain wrong).

That being said, iOS is more or less similar, but we get around the duplicated issue since importing the resulting XLIFF files has to happen manually (so far) anyways. There might be other platforms out there where such an exclusion also makes sense.

Regardless, all in all we're very happy with PhraseApp, as it delivers exactly what we need to have a good, productive flow when localizing our apps, so this issue would just be the icing on the cake. 😃 👍 Btw, your documentation articles etc. are very helpful, too!

**Comment by theSoenke** [comment]
Thank you very much for your great feedback! We appreciate it very much :) 
There are definitely some cases where it makes a lot of sense to exclude some locales and I will add it to our internal feature requests for prioritization

**Comment by sp00ne** [comment]
Right now, this creates `values-en-US` for us since the locale is not just `en`. This causes a build error for our project and therefore not just icing ont the cake 🙁

**Comment by Papashkin** [comment]
I'm using  Brazilian Portuguese translation in Android, but here is difference between region locales in Phrase and Android: `pt-BR` in Phrase and `pt-rBR` in Android.
I know how to pull data with pt-BR locale to `values-pt-rBR` folder.
But also I receive after pulling the `values-pt-BR` folder, which crash my builds because incorrect style and Android doesn't understand it.
What should I do in that case? The variant with `exclude` or `exclude_id` in params will be preferable for me, but may be you know another solution.

Best regards,
Pavel A.

**Comment by theSoenke** [comment]
@Papashkin In case you've not already seen in the second issue before you can list the locales that should be pulled in your .phraseapp.yml config like this:

```yml
  pull:
    targets:
    - file: ./app/src/main/res/values-pt-rBR/strings.xml
      params:
        file_format: xml
        locale_id: pt-BR
    - file: ./app/src/main/res/values-en/strings.xml
      params:
        file_format: xml
        locale_id: en
```

This way you have full control over which locales will get pulled
