### ISSUE TITLE
When branching, locales get new id's

### ISSUE THREAD

**Issue by sp00ne** [phrase/phraseapp-client#174]
# Issue
I have a `phraseapp.yml` file that looks like this:
```
phraseapp:
...
  file_format: xml
  push:
    sources:
      - file: "./app/src/main/res/values/strings.xml"
        params:
          file_format: xml
          locale_id: 88df8852c829d975470f97feb607c8e8
  pull:
    targets:
      - file: "./app/src/main/res/values/strings.xml"
        params:
          locale_id: 88df8852c829d975470f97feb607c8e8
      - file: "./app/src/main/res/values-<locale_code>/strings.xml"
```

If I write `phraseapp push --branch test` , it will fail since the `locale_ids` will be different than that of the original branch. This does not seem to me as intended behavior, I have already specified the branch onto which I want to push, so why should I regenerate my .yml file for each branch? 

I will fallback to the plain-text version ("en" in this case), but I'd guess this is a bug
