### ISSUE TITLE
Android: pull/push different files for plain strings and string arrays

### ISSUE THREAD

**Issue by serggl** [phrase/phraseapp-client#18]
is it possible?
I don't like having them in a single `strings.xml` file, I used to split them into `strings.xml` and `arrays.xml`

How do I achieve this using this tool?

**Comment by gfrey** [comment]
Yes, it is. Upload the files with a tag. This tag can then be used on downloading to put the different keys into seperate files again.

Use something like the following your `.phraseapp.yml`:
```yml
phraseapp:
  access_token: [your token]
  file_format: xml
  project_id: [your project]
  push:
    sources:
    - file: ./app/src/main/res/values/strings.xml
      params:
        locale_id: en
        tags: strings
    - file: ./app/src/main/res/values/arrays.xml
      params:
        locale_id: en
        tags: arrays
  pull:
    targets:
    - file: ./app/src/main/res/values-<locale_name>/strings.xml
      params:
          tag: strings
    - file: ./app/src/main/res/values-<locale_name>/arrays.xml
      params:
          tag: arrays
```

Does that help?
