### ISSUE TITLE
Feature request: Allow setting format_options globally, not per target

### ISSUE THREAD

**Issue by carstenhag** [phrase/phraseapp-client#194]
Hello, for our apps we have one big .phraseapp.yml file. For each file, we currently have to set the  formatting options. I tried setting the format_options to the beneath the file_format parameter, but that did not work.

It would be really helpful if you could add this functionality :)

```yml
phraseapp:
  access_token: xyz123
  file_format: xml
  pull:
    targets:
      - file: ./app/src/main/res/values/strings.xml
        project_id: xyz123 
        params:
          locale_id: xyz123
          format_options:
            escape_linebreaks: true

     # ...
     # 58 more files
```
