### ISSUE TITLE
Make en translations in Android project default

### ISSUE THREAD

**Issue by vanniktech** [phrase/phraseapp-client#27]
Right now our pull config looks like this:

```yaml
pull:
    targets:
    - {file: ./app/src/main/res/values-<locale_name>/strings.xml}
```

Which results in:

> Downloaded en to app/src/main/res/values-en/strings.xml
Downloaded de to app/src/main/res/values-de/strings.xml
Downloaded vi to app/src/main/res/values-vi/strings.xml
Downloaded pl to app/src/main/res/values-pl/strings.xml
Downloaded ar to app/src/main/res/values-ar/strings.xml
Downloaded es to app/src/main/res/values-es/strings.xml
Downloaded id to app/src/main/res/values-id/strings.xml
Downloaded pt to app/src/main/res/values-pt/strings.xml
Downloaded ru to app/src/main/res/values-ru/strings.xml
Downloaded tr to app/src/main/res/values-tr/strings.xml
Downloaded zh to app/src/main/res/values-zh/strings.xml
Downloaded sv to app/src/main/res/values-sv/strings.xml

Is there any way to get `en` into `app/src/main/res/values/strings.xml`?

The problem is that if a translated string is only present in `values-en` and you use German for instance it can't find anything and the app will crash during testing.

**Comment by gfrey** [comment]
Hi,

you could use a dedicated download target for the english locale:

```
  pull:
    targets:
    - file: ./app/src/main/res/values-<locale_name>/strings.xml
    - file: ./app/src/main/res/values/strings.xml
      params:
        locale_id: en
```

Hope that helps,
Gereon
