### ISSUE TITLE
Error message for pull command when filtering by tag that does not exist

### ISSUE THREAD

**Issue by theSoenke** [phrase/phraseapp-client#62]
When pushing a locale with a tag specified and the tag does not exists the upload fails with:

`ERROR: 404 - Resource Not Found`

Error message does not explain the reason for the upload failure. Showing the reason for the failure would make it simpler to find the problem

**Comment by tobstarr** [comment]
@alexanderwilling could you have a look at this?

**Comment by alexanderwilling** [comment]
So, I just tested this.

`.phraseapp.yml`:
```
phraseapp:
  host: http://localhost:3000/api
  access_token: c195ae2922041fe06efa95fe615cb38783c3e2734ecfe00dbee6b4f38650752b
  project_id: 4c3f196db9d00659d6addb4dac4fccef
  push:
    sources:
    - file: ./config/locales/<locale_name>.yml
      params:
        file_format: yml
        tags: batman
  pull:
    targets:
    - file: ./config/locales/<locale_name>.yml
      params:
        file_format: yml
```

`config/locales/en.yml`:
```
---
en:
  nananana: 'mimimi'
```

I deleted all tags and all keys in the project, then did a `phraseapp-client push`, and only got `Uploaded config/locales/en.yml successfully.` The tag `batman` shows up in the web interface and `nananana` has both the `batman` tag as well as a tag for the upload attached:

```
[alex@macbook asd]$ phraseapp-client keys list
You're running a development version (DEV) of the PhraseApp client! Latest version is 1.3.0

[{"created_at":"2016-12-19T09:42:08Z","data_type":"","description":"","id":"2b4f4baf015ced171cdeca58a82773d2","name":"nananana","name_hash":"7d60b15bc13904c2220db021100d56bc","plural":false,"tags":["upload-20161219_094208","batman"],"updated_at":"2016-12-19T09:42:08Z"}]
```
