### ISSUE TITLE
Region-specific languages use wrong Android resource specifier

### ISSUE THREAD

**Issue by benlacey** [phrase/phraseapp-client#81]
Using the configuration example from the [phraseapp init](https://phraseapp.com/docs/developers/cli/configuration/#init) documentation to download Android strings.xml files, any region-specific language like en-GB does not get downloaded to the proper language-specific folder that Android expects:

Expected: `Downloaded en-GB to ./res/values-en-rGB/strings.xml`
Actual: `Downloaded en-GB to ./res/values-en-GB/strings.xml`

This is according to the table in the Android resource specifier documentation [here](https://developer.android.com/guide/topics/resources/providing-resources.html#AlternativeResources).

I can fix this by individually specifying which languages to download to specific destination files, but it seems like the minimal configuration used in the init documentation should work.  Sort of feels like I've missed something obvious, so let me know if that's the case!

**Comment by sacry-dyn** [comment]
@benlacey thank you for reaching out. The PhraseApp Client is a more generic way to specifying all different configuration formats that are out there. You can easily edit it after the `init` like you described. The feature you are describing is part of our AndroidStudio plugin 

https://github.com/phrase/phraseapp-AndroidStudio

**Comment by benlacey** [comment]
@sacry-dyn That makes sense, thanks.  We're using Xamarin instead of Android Studio, so the plugin isn't an option, but the cli is working fine with the manually specified config so I'm happy for this to be closed - thanks for the explanation!

**Comment by Papashkin** [comment]
I have the same issue, but unfortunately the PhraseApp doesn't work correctly in Android Studio last stable version (for more information please check [this issue](https://github.com/phrase/phraseapp-AndroidStudio/issues/12)).
Code like this:
```
push:
    sources:
         - file: ./app/src/main/res/values-pt-rBR/strings.xml
           params:
                locale_id: pt-BR
                file_format: xml
```

doesn't help me too.
What should I do?

**Comment by theSoenke** [comment]
Hi @Papashkin, your example only includes the push part. But you are having trouble during pull right? To download the locales in the correct locations you can list the locales one by one with a custom path.

For example:
```yml
  pull:
    targets:
    - file: ./app/src/main/res/values-pt-rBR/strings.xml
      params:
        file_format: xml
        locale_id: en

```

Then you can add multiple targets to pull for each locale.

Does this already help?
