### ISSUE TITLE
YAML Merge syntax is not supported for the localization files

### ISSUE THREAD

**Issue by serggl** [phrase/phraseapp-client#87]
This is more likely a feature request, but currently Im facing this as a bug, so I would like to post it here.

Im using PhraseApp for the Rails app and Im uploading translations in `yml` format and Im using YAML merge syntax (http://yaml.org/type/merge.html) to structure my texts and to avoid copy-pasting. 
Here is a sample:
```
en:
  describe: &describe
    a: Something

  describe-other:
    <<: *describe
    b: Other
```

This should be translated with YAML parser to:
```
en:
  describe:
    a: Something

  describe-other:
    a: Something
    b: Other
```

But this is not happening when Im upload YML file via CLI. There should be 3 keys created with such upload:
```
describe.a
describe-other.a
describe-other.b
``` 
Instead only 2 are being created:
```
describe.a
describe-other.b
``` 

If I change uploaded file to
```
en:
  describe: &describe
    a: Something

  describe-other:
    <<: *describe
```

it will also create 2 keys: 
```
describe.a
describe-other
``` 
but the last one will hold a blank value

P.S. here is `.phraseapp.yml` Im using
```
phraseapp:
  file_format: yml
  project_id: xxxxxxxx
  defaults:
    keys/list:
      sort: name
      order: asc
  push:
    sources:
      -
        file: ./config/locales/test.en.yml
        params:
          locale_id: yyyyyyyy
          tags: test
```
